// Code generated by gen/generate.rs — DO NOT EDIT.
// Re-run: cargo run --bin generate

use std::sync::Arc;

use crate::error::Rail0Error;
use crate::http::HttpClient;
use crate::types::PaymentMethod;
use crate::types_gen::{ListWalletsParams, PaginatedWalletTokens, WalletToken};

/// Merchant configuration operations.
pub struct AccountsClient {
    http: Arc<HttpClient>,
}

impl AccountsClient {
    pub(crate) fn new(http: Arc<HttpClient>) -> Self {
        Self { http }
    }

    /// Return the active payment methods (chain + token + wallet) for the given account.
    pub async fn payment_methods(&self, account_id: &str) -> Result<Vec<PaymentMethod>, Rail0Error> {
        self.http
            .get(&format!("/accounts/{account_id}/payment-methods"))
            .await
    }

    /// List wallet tokens for an account. Public — no JWT required.
    pub async fn wallets(
        &self,
        account_id: &str,
        params: ListWalletsParams,
    ) -> Result<PaginatedWalletTokens, Rail0Error> {
        let mut qs = String::new();
        if let Some(v) = params.chain_id {
            push_param(&mut qs, "chain_id", &v.to_string());
        }
        if let Some(v) = &params.chain_slug {
            push_param(&mut qs, "chain_slug", v);
        }
        if let Some(v) = &params.token_symbol {
            push_param(&mut qs, "token_symbol", v);
        }
        if let Some(v) = params.active {
            push_param(&mut qs, "active", if v { "true" } else { "false" });
        }
        if let Some(v) = params.page {
            push_param(&mut qs, "page", &v.to_string());
        }
        if let Some(v) = params.per_page {
            push_param(&mut qs, "per_page", &v.to_string());
        }
        let path = if qs.is_empty() {
            format!("/accounts/{account_id}/wallets")
        } else {
            format!("/accounts/{account_id}/wallets?{qs}")
        };
        self.http.get(&path).await
    }

    /// Fetch a single wallet token by id for the given account.
    pub async fn wallet(&self, account_id: &str, wallet_id: &str) -> Result<WalletToken, Rail0Error> {
        self.http
            .get(&format!("/accounts/{account_id}/wallets/{wallet_id}"))
            .await
    }
}

fn push_param(qs: &mut String, key: &str, value: &str) {
    if !qs.is_empty() {
        qs.push('&');
    }
    qs.push_str(key);
    qs.push('=');
    qs.push_str(value);
}
