// Code generated by gen/generate.rs — DO NOT EDIT.
// Re-run: cargo run --bin generate

use std::sync::Arc;

use crate::error::Rail0Error;
use crate::http::HttpClient;
use crate::types::{
    CapturePaymentRequest, CreatePaymentRequest, CreatePaymentResponse,
    PayerSignatureRequest, PayerSignatureResponse, PrepareTransactionResponse,
    RefundPayloadRequest, RefundPrepareResponse, ReleaseRequest, SubmitTransactionRequest,
};
use crate::types_gen::{
    ListPaymentsParams, ListTransactionsParams, PaginatedPayments, PaginatedTransactions,
    PaymentSummary, SubmitTransactionAcceptedResponse,
};

/// Payment lifecycle operations.
pub struct PaymentsClient {
    http: Arc<HttpClient>,
}

impl PaymentsClient {
    pub(crate) fn new(http: Arc<HttpClient>) -> Self {
        Self { http }
    }

    /// List payments for the authenticated wallet (requires JWT).
    pub async fn list(&self, params: ListPaymentsParams) -> Result<PaginatedPayments, Rail0Error> {
        let mut qs = String::new();
        if let Some(v) = &params.status {
            push_param(&mut qs, "status", v);
        }
        if let Some(v) = &params.mode {
            push_param(&mut qs, "mode", v);
        }
        if let Some(v) = &params.payer {
            push_param(&mut qs, "payer", v);
        }
        if let Some(v) = &params.payee {
            push_param(&mut qs, "payee", v);
        }
        if let Some(v) = &params.token {
            push_param(&mut qs, "token", v);
        }
        if let Some(v) = params.page {
            push_param(&mut qs, "page", &v.to_string());
        }
        if let Some(v) = params.per_page {
            push_param(&mut qs, "per_page", &v.to_string());
        }
        let path = if qs.is_empty() {
            "/payments".to_owned()
        } else {
            format!("/payments?{qs}")
        };
        self.http.get(&path).await
    }

    /// Create a payment intent. Returns the EIP-712 signing_payload for the payer to sign.
    pub async fn create_payment(
        &self,
        params: &CreatePaymentRequest,
    ) -> Result<CreatePaymentResponse, Rail0Error> {
        self.http.post("/payments", params).await
    }

    /// Fetch current payment state (DB status + live on-chain amounts).
    pub async fn get(&self, payment_id: &str) -> Result<PaymentSummary, Rail0Error> {
        self.http.get(&format!("/payments/{payment_id}")).await
    }

    /// List on-chain transactions for a payment.
    pub async fn transactions(
        &self,
        payment_id: &str,
        params: ListTransactionsParams,
    ) -> Result<PaginatedTransactions, Rail0Error> {
        let mut qs = String::new();
        if let Some(v) = &params.operation {
            push_param(&mut qs, "operation", v);
        }
        if let Some(v) = &params.status {
            push_param(&mut qs, "status", v);
        }
        if let Some(v) = params.page {
            push_param(&mut qs, "page", &v.to_string());
        }
        if let Some(v) = params.per_page {
            push_param(&mut qs, "per_page", &v.to_string());
        }
        let path = if qs.is_empty() {
            format!("/payments/{payment_id}/transactions")
        } else {
            format!("/payments/{payment_id}/transactions?{qs}")
        };
        self.http.get(&path).await
    }

    /// Submit the payer's EIP-712 signature (v, r, s).
    pub async fn sign(
        &self,
        payment_id: &str,
        params: &PayerSignatureRequest,
    ) -> Result<PayerSignatureResponse, Rail0Error> {
        self.http
            .put(&format!("/payments/{payment_id}/sign"), params)
            .await
    }

    // ── Authorize ─────────────────────────────────────────────────────────────

    /// Prepare the unsigned authorize() transaction. Called by the payee.
    pub async fn authorize_prepare(
        &self,
        payment_id: &str,
    ) -> Result<PrepareTransactionResponse, Rail0Error> {
        self.http
            .post(&format!("/payments/{payment_id}/authorize/prepare"), &())
            .await
    }

    /// Broadcast a signed authorize transaction (HTTP 202, async). Called by the payee.
    pub async fn authorize(
        &self,
        payment_id: &str,
        params: &SubmitTransactionRequest,
    ) -> Result<SubmitTransactionAcceptedResponse, Rail0Error> {
        self.http
            .post(&format!("/payments/{payment_id}/authorize"), params)
            .await
    }

    // ── Charge ────────────────────────────────────────────────────────────────

    /// Prepare the unsigned charge() transaction (one-shot, no escrow). Called by the payee.
    pub async fn charge_prepare(
        &self,
        payment_id: &str,
    ) -> Result<PrepareTransactionResponse, Rail0Error> {
        self.http
            .post(&format!("/payments/{payment_id}/charge/prepare"), &())
            .await
    }

    /// Broadcast a signed charge transaction (HTTP 202, async). Called by the payee.
    pub async fn charge(
        &self,
        payment_id: &str,
        params: &SubmitTransactionRequest,
    ) -> Result<SubmitTransactionAcceptedResponse, Rail0Error> {
        self.http
            .post(&format!("/payments/{payment_id}/charge"), params)
            .await
    }

    // ── Capture ───────────────────────────────────────────────────────────────

    /// Build the unsigned capture() transaction. Called by the payee.
    pub async fn capture_prepare(
        &self,
        payment_id: &str,
        params: &CapturePaymentRequest,
    ) -> Result<PrepareTransactionResponse, Rail0Error> {
        self.http
            .post(&format!("/payments/{payment_id}/capture/prepare"), params)
            .await
    }

    /// Broadcast a signed capture transaction (HTTP 202, async). Called by the payee.
    pub async fn capture(
        &self,
        payment_id: &str,
        params: &SubmitTransactionRequest,
    ) -> Result<SubmitTransactionAcceptedResponse, Rail0Error> {
        self.http
            .post(&format!("/payments/{payment_id}/capture"), params)
            .await
    }

    // ── Void ──────────────────────────────────────────────────────────────────

    /// Build the unsigned void() transaction. Called by the payee.
    pub async fn void_prepare(
        &self,
        payment_id: &str,
    ) -> Result<PrepareTransactionResponse, Rail0Error> {
        self.http
            .post(&format!("/payments/{payment_id}/void/prepare"), &())
            .await
    }

    /// Broadcast a signed void transaction (HTTP 202, async). Called by the payee.
    pub async fn void(
        &self,
        payment_id: &str,
        params: &SubmitTransactionRequest,
    ) -> Result<SubmitTransactionAcceptedResponse, Rail0Error> {
        self.http
            .post(&format!("/payments/{payment_id}/void"), params)
            .await
    }

    // ── Release ───────────────────────────────────────────────────────────────

    /// Build the unsigned release() transaction.
    pub async fn release_prepare(
        &self,
        payment_id: &str,
        params: &ReleaseRequest,
    ) -> Result<PrepareTransactionResponse, Rail0Error> {
        self.http
            .post(&format!("/payments/{payment_id}/release/prepare"), params)
            .await
    }

    /// Broadcast a signed release transaction (HTTP 202, async).
    pub async fn release(
        &self,
        payment_id: &str,
        params: &SubmitTransactionRequest,
    ) -> Result<SubmitTransactionAcceptedResponse, Rail0Error> {
        self.http
            .post(&format!("/payments/{payment_id}/release"), params)
            .await
    }

    // ── Refund (EIP-3009) ─────────────────────────────────────────────────────

    /// Two-phase EIP-3009 refund flow. Called by the payee.
    ///
    /// Phase 1 — set only `amount`: returns the EIP-3009 signing payload.
    /// Phase 2 — set `amount` plus `v`, `r`, `s`: returns the unsigned on-chain refund transaction.
    pub async fn refund_prepare(
        &self,
        payment_id: &str,
        params: &RefundPayloadRequest,
    ) -> Result<RefundPrepareResponse, Rail0Error> {
        self.http
            .post(&format!("/payments/{payment_id}/refund/prepare"), params)
            .await
    }

    /// Broadcast a signed refund transaction (HTTP 202, async). Called by the payee.
    pub async fn refund(
        &self,
        payment_id: &str,
        params: &SubmitTransactionRequest,
    ) -> Result<SubmitTransactionAcceptedResponse, Rail0Error> {
        self.http
            .post(&format!("/payments/{payment_id}/refund"), params)
            .await
    }
}

fn push_param(qs: &mut String, key: &str, value: &str) {
    if !qs.is_empty() {
        qs.push('&');
    }
    qs.push_str(key);
    qs.push('=');
    qs.push_str(value);
}
