// Code generated by gen/generate.rs — DO NOT EDIT.
// Re-run `cargo run --bin generate` after updating rail0-api/docs/openapi.json.

#![allow(dead_code)]

use serde::{Deserialize, Serialize};

/// A RAIL0 merchant account.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Account {
    pub active: bool,
    pub created_at: String,
    pub email: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub fee_bps: Option<u32>,
    pub id: String,
    pub name: String,
    pub slug: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
}

/// Amount to capture from escrow. May be less than `capturable_amount` for a partial capture.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CapturePaymentRequest {
    /// Amount to capture (in token base units). Must be > 0 and <= current capturable_amount.
    pub amount: String,
}

/// Payload sent by the rail0-indexer when an on-chain event is detected for a known transaction.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ConfirmTransactionRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    /// Token amount from the on-chain event. Required for `captured` and `refunded` events; optional for others.
    pub amount: Option<String>,
    /// Block number in which the transaction was confirmed.
    pub block_number: u32,
    /// The on-chain event emitted by the RAIL0 contract.
    pub event_type: String,
    /// The rail0_id of the payment this transaction belongs to.
    pub payment_id: String,
}

/// Parameters needed to create a payment intent.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreatePaymentRequest {
    /// EVM chain ID of the target network.
    pub chain_id: u32,
    #[serde(skip_serializing_if = "Option::is_none")]
    /// Optional human-readable payment label visible to the payer (e.g. "Order #123 — Acme Store").
    pub description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    /// Arbitrary key-value data for custom reconciliation. Set at creation and immutable. Max 4 KB.
    pub metadata: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    /// `authorize` — funds held in escrow, captured later. `charge` — one-shot: funds immediately distributed. The two modes use different EIP-3009 nonce prefixes; a signature for one cannot be reused for the other.
    pub mode: Option<String>,
    pub payment: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreatePaymentResponse {
    pub chain_id: u32,
    /// EIP-712 hash of the Payment struct. Commits the signature to the exact payment terms.
    pub config_hash: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    /// Optional human-readable payment label.
    pub description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    /// Arbitrary key-value data attached at creation for custom reconciliation.
    pub metadata: Option<serde_json::Value>,
    pub payment: String,
    /// Address of the RAIL0 contract on the target chain.
    pub rail0_contract: String,
    /// Unique identifier for this payment.
    pub rail0_id: String,
    pub signing_payload: String,
}

/// Message fields for the EIP-3009 TransferWithAuthorization signature.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EIP3009Message {
    pub from: String,
    /// keccak256(NONCE_PREFIX, rail0_id, config_hash). Binds the signature to the exact config and operation type.
    pub nonce: String,
    /// RAIL0 contract address.
    pub to: String,
    #[serde(rename = "validAfter")]
    /// Always '0' for RAIL0 flows.
    pub valid_after: String,
    #[serde(rename = "validBefore")]
    /// Equals authorization_expiry.
    pub valid_before: String,
    pub value: String,
}

/// EIP-712 domain for the token contract.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EIP712Domain {
    #[serde(rename = "chainId")]
    pub chain_id: u32,
    pub name: String,
    #[serde(rename = "verifyingContract")]
    /// Token contract address.
    pub verifying_contract: String,
    pub version: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Error {
    /// Machine-readable error code (snake_case).
    pub code: String,
    /// Human-readable error description.
    pub message: String,
}

/// Current state of a payment record.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GetPaymentResponse {
    pub amount: String,
    pub authorization_expiry: i64,
    pub chain_id: u32,
    #[serde(skip_serializing_if = "Option::is_none")]
    /// Optional human-readable payment label.
    pub description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    /// Machine-readable failure reason. Present only when status=failed.
    pub failure_code: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    /// Human-readable failure description. Present only when status=failed.
    pub failure_message: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    /// Hash of the most recently broadcast transaction.
    pub last_broadcast_hash: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    /// Arbitrary key-value data attached at creation for custom reconciliation.
    pub metadata: Option<serde_json::Value>,
    pub mode: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    /// Live on-chain amounts. Present when status is authorized, captured, voided, released, charged, or refunded.
    pub on_chain: Option<serde_json::Value>,
    pub payee: String,
    pub payer: String,
    pub rail0_id: String,
    pub refund_expiry: i64,
    /// Current lifecycle state.
    pub status: String,
    pub token: String,
}

/// EIP-712 signature over the `signing_payload` returned by `POST /payments`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PayerSignatureRequest {
    /// 65-byte secp256k1 signature (0x-prefixed, 132 chars): r (32 bytes) + s (32 bytes) + v (1 byte).
    pub signature: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PayerSignatureResponse {
    pub rail0_id: String,
    /// The address recovered from the signature — should match `payment.payer`.
    pub recovered_payer: String,
    /// Confirms the signature was accepted and stored.
    pub status: String,
}

/// Immutable payment configuration that maps 1-to-1 to the RAIL0 `Payment` Solidity struct.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PaymentConfig {
    /// Exact amount the payer commits to pay (in token base units).
    pub amount: String,
    /// Unix timestamp (seconds). Capture must happen before this; release opens after.
    pub authorization_expiry: i64,
    /// Fee in basis points (0 = no fee, 10000 = 100%).
    pub fee_bps: u32,
    /// Recipient of the fee on each capture. Use the zero address when fee_bps is 0.
    pub fee_receiver: String,
    /// Account address. Authorized to capture, void, and refund.
    pub payee: String,
    /// Buyer address. Funds are pulled from this address.
    pub payer: String,
    /// Unix timestamp (seconds). Refund must happen before this. Must be >= authorization_expiry.
    pub refund_expiry: i64,
    /// EIP-3009-capable ERC-20 token address (must be accepted by the RAIL0 deployment).
    pub token: String,
}

/// Buyer-supplied payment parameters. Policy fields (authorization_expiry, refund_expiry, fee_bps, fee_receiver) are fixed API configuration applied server-side.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PaymentInput {
    /// Amount to pay (in token base units).
    pub amount: String,
    /// Account wallet address (wallet_address from GET /accounts/{id}/payment-methods).
    pub payee: String,
    /// Buyer address. Funds are pulled from this address.
    pub payer: String,
    /// ERC-20 token address (token_address from GET /accounts/{id}/payment-methods).
    pub token: String,
}

/// A single accepted payment method for a account: one (chain, token, wallet) combination.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PaymentMethod {
    pub chain_id: u32,
    pub chain_name: String,
    pub default: bool,
    pub id: u32,
    /// ERC-20 token contract address on the chain.
    pub token_address: String,
    pub token_decimals: u32,
    pub token_id: u32,
    pub token_symbol: String,
    /// Account wallet address to use as `payee` in PaymentConfig.
    pub wallet_address: String,
}

/// An unsigned EIP-1559 transaction ready for the payee to sign.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PrepareTransactionResponse {
    #[serde(rename = "chainId")]
    pub chain_id: u32,
    /// ABI-encoded calldata (informational).
    pub data: String,
    #[serde(rename = "gasLimit")]
    pub gas_limit: String,
    #[serde(rename = "maxFeePerGas")]
    pub max_fee_per_gas: String,
    #[serde(rename = "maxPriorityFeePerGas")]
    pub max_priority_fee_per_gas: String,
    pub nonce: u32,
    /// Target contract address (informational).
    pub to: String,
    /// Server-side Transaction row ID. Passed back in the submit body to link the signed tx to the prepare step.
    pub transaction_id: String,
    /// RLP-encoded unsigned EIP-1559 transaction (type 2).
    pub unsigned_transaction: String,
}

/// Amount to refund to the payer.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RefundPaymentRequest {
    /// Amount to refund (in token base units). Must be > 0 and <= current refundable_amount.
    pub amount: String,
}

/// Optional parameters for the release prepare step.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ReleaseRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    /// Address of the account that will sign and submit the release transaction. Defaults to the payment's `payee` if omitted.
    pub caller_address: Option<String>,
}

/// EIP-712 typed-data structure that the payer (or payee for refund) must sign. Pass verbatim to `eth_signTypedData_v4`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SigningPayload {
    pub domain: String,
    pub message: String,
    #[serde(rename = "primaryType")]
    pub primary_type: String,
    pub types: serde_json::Value,
}

/// Acknowledgement that the transaction has been enqueued. Poll `GET /payments/{rail0_id}` for the final outcome.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SubmitTransactionAcceptedResponse {
    /// Payment identifier.
    pub rail0_id: String,
    /// Always `submitting` — the worker has not yet received the on-chain receipt.
    pub status: String,
}

/// Signed transaction to broadcast on-chain.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SubmitTransactionRequest {
    /// RLP-encoded signed EIP-1559 transaction as returned by `eth_signTransaction`.
    pub signed_transaction: String,
}

/// A blockchain transaction associated with a payment.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Transaction {
    #[serde(skip_serializing_if = "Option::is_none")]
    /// Token amount processed. `null` until confirmed.
    pub amount: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    /// Block number in which the transaction was mined. `null` until confirmed.
    pub block_number: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    /// ISO 8601 timestamp when the transaction was confirmed. `null` until confirmed.
    pub confirmed_at: Option<String>,
    /// Protocol fee deducted. `"0"` until confirmed.
    pub fee_amount: String,
    /// Smart contract operation executed by this transaction.
    pub operation: String,
    /// Parent payment identifier.
    pub rail0_id: String,
    /// `submitted` = broadcast, awaiting confirmation. `confirmed` = mined successfully. `failed` = reverted.
    pub status: String,
    /// ISO 8601 timestamp when the transaction was broadcast on-chain.
    pub submitted_at: String,
    /// Keccak256 hash of the broadcast transaction.
    pub transaction_hash: String,
}


/// A wallet token configuration linking a wallet address to a specific token on a chain.
/// Hardcoded — not all spec versions include this schema.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WalletToken {
    pub id: String,
    pub wallet_id: String,
    pub address: String,
    pub default: bool,
    pub active: bool,
    pub token_id: String,
    pub token_symbol: String,
    pub token_address: String,
    pub token_decimals: u32,
    pub chain_id: u32,
    pub chain_name: String,
    pub chain_slug: String,
}

/// Summary of a payment returned by list and get endpoints.
/// Hardcoded — not all spec versions include this schema.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PaymentSummary {
    pub rail0_id: String,
    pub status: String,
    pub mode: String,
    pub amount: String,
    pub payer: String,
    pub payee: String,
    pub token: String,
    pub authorization_expiry: u64,
    pub refund_expiry: u64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metadata: Option<serde_json::Value>,
    pub created_at: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub on_chain: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub failure_code: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub failure_message: Option<String>,
}

/// A single on-chain transaction associated with a payment.
/// Hardcoded — not all spec versions include this schema.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TransactionRecord {
    pub id: String,
    pub operation: String,
    pub status: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub transaction_hash: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub amount: Option<String>,
    pub fee_amount: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub block_number: Option<u64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error_reason: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pending_at: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub submitted_at: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub confirmed_at: Option<String>,
}

/// Pagination metadata returned by list endpoints.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PageMeta {
    pub page: u32,
    pub per_page: u32,
    pub total: u32,
}

/// Paginated list of WalletToken entries.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PaginatedWalletTokens {
    pub data: Vec<WalletToken>,
    pub meta: PageMeta,
}

/// Paginated list of PaymentSummary entries.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PaginatedPayments {
    pub data: Vec<PaymentSummary>,
    pub meta: PageMeta,
}

/// Paginated list of TransactionRecord entries.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PaginatedTransactions {
    pub data: Vec<TransactionRecord>,
    pub meta: PageMeta,
}

/// Optional query parameters for listing wallet tokens.
#[derive(Debug, Default)]
pub struct ListWalletsParams {
    pub chain_id: Option<u32>,
    pub chain_slug: Option<String>,
    pub token_symbol: Option<String>,
    pub active: Option<bool>,
    pub page: Option<u32>,
    pub per_page: Option<u32>,
}

/// Optional query parameters for listing payments.
#[derive(Debug, Default)]
pub struct ListPaymentsParams {
    pub status: Option<String>,
    pub mode: Option<String>,
    pub payer: Option<String>,
    pub payee: Option<String>,
    pub token: Option<String>,
    pub page: Option<u32>,
    pub per_page: Option<u32>,
}

/// Optional query parameters for listing transactions.
#[derive(Debug, Default)]
pub struct ListTransactionsParams {
    pub operation: Option<String>,
    pub status: Option<String>,
    pub page: Option<u32>,
    pub per_page: Option<u32>,
}
