// Code generated by gen/generate.rs — DO NOT EDIT.
// Re-run `cargo run --bin generate` after updating rail0-api/doc/openapi.json.

#![allow(dead_code)]

use serde::{Deserialize, Serialize};

/// Amount to approve on the token contract. Setting this to the maximum expected refund (or `type(uint256).max` for unlimited) avoids repeated approvals.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ApproveRequestGen {
    /// Allowance to grant the RAIL0 contract (in token base units). Use '115792089237316195423570985008687907853269984665640564039457584007913129639935' for unlimited approval.
    pub amount: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ApproveResponseGen {
    /// Approved allowance amount.
    pub amount: String,
    /// RAIL0 contract address that was approved as spender.
    pub spender: String,
    /// Token contract on which the approval was set.
    pub token: String,
    /// On-chain transaction hash of the `approve()` call.
    pub transaction_hash: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AuthorizePaymentResponseGen {
    /// Unix timestamp after which capture is no longer possible and release becomes available.
    pub authorization_expiry: Option<i64>,
    /// Amount now held in escrow and available for capture (equals the authorized amount).
    pub capturable_amount: String,
    /// Payment identifier.
    pub payment_id: String,
    /// On-chain transaction hash of the `authorize()` call.
    pub transaction_hash: String,
}

/// Amount to capture from escrow. May be less than the total capturable balance for a partial capture.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CapturePaymentRequestGen {
    /// Amount to capture (in token base units). Must be > 0 and <= current capturableAmount.
    pub amount: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CapturePaymentResponseGen {
    /// Unix timestamp after which further captures are no longer possible.
    pub authorization_expiry: Option<i64>,
    /// Remaining escrowed amount still available for future captures.
    pub capturable_amount: String,
    /// Gross amount captured in this call (before fee deduction). Matches the `amount` parameter passed to the contract.
    pub captured_amount: String,
    /// Fee deducted from this capture and sent to feeReceiver. '0' when feeBps is 0.
    pub fee_amount: Option<String>,
    /// Payment identifier.
    pub payment_id: String,
    /// Cumulative amount already captured and eligible for refund (until refundExpiry).
    pub refundable_amount: String,
    /// On-chain transaction hash of the `capture()` call.
    pub transaction_hash: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ChargePaymentResponseGen {
    /// Gross amount charged (before fee deduction). Matches the `amount` parameter passed to the contract.
    pub charged_amount: String,
    /// Fee sent to feeReceiver. '0' when feeBps is 0.
    pub fee_amount: String,
    /// Payment identifier.
    pub payment_id: String,
    /// Amount eligible for refund (equals chargedAmount; the full gross amount is tracked as refundable by the contract).
    pub refundable_amount: String,
    /// On-chain transaction hash of the `charge()` call.
    pub transaction_hash: String,
}

/// Parameters needed to create a payment intent. The API generates a unique `paymentId`, applies its fixed policy config, and constructs the EIP-712 signing payload.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CreatePaymentRequestGen {
    /// EVM chain ID of the target network.
    pub chain_id: u32,
    /// `authorize` — funds are held in escrow and captured later by the payee. `charge` — one-shot: funds are immediately distributed to payee and feeReceiver with no escrow window. The two modes use different EIP-3009 nonce prefixes; a signature produced for one cannot be submitted for the other.
    pub mode: Option<String>,
    pub payment: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CreatePaymentResponseGen {
    /// EVM chain ID.
    pub chain_id: u32,
    /// EIP-712 hash of the Payment struct over the RAIL0 domain. Commits the signature to the exact payment terms.
    pub config_hash: String,
    pub payment: String,
    /// Unique identifier for this payment (generated by the API, bytes32 hex).
    pub payment_id: String,
    /// Address of the RAIL0 contract on the target chain.
    pub rail0_contract: String,
    pub signing_payload: String,
}

/// Message fields for the EIP-3009 TransferWithAuthorization typed-data signature.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct EIP3009MessageGen {
    /// Payer address (token sender).
    pub from: String,
    /// keccak256(NONCE_PREFIX, paymentId, configHash) where NONCE_PREFIX is `RAIL0.AUTHORIZE` for mode=authorize and `RAIL0.CHARGE` for mode=charge. Binds the signature to the exact Payment configuration and operation type.
    pub nonce: String,
    /// RAIL0 contract address (token recipient / escrow).
    pub to: String,
    /// Always '0' for RAIL0 authorize flows.
    pub valid_after: String,
    /// Equals payment.authorizationExpiry (Unix timestamp as string).
    pub valid_before: String,
    /// Amount to transfer (same as the requested authorization amount).
    pub value: String,
}

/// EIP-712 domain for the token contract (used by EIP-3009 TransferWithAuthorization).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct EIP712DomainGen {
    /// EVM chain ID.
    pub chain_id: u32,
    /// Token's EIP-712 domain name.
    pub name: String,
    /// Token contract address.
    pub verifying_contract: String,
    /// Token's EIP-712 domain version.
    pub version: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ErrorGen {
    /// Machine-readable error code.
    pub code: String,
    /// Human-readable error description.
    pub message: String,
}

/// EIP-712 signature over the `signingPayload` returned by `POST /payments`. Browser wallets return this directly from `eth_signTypedData_v4`; backends produce it with any EIP-712 library. The on-chain verification only checks the recovered address.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PayerSignatureRequestGen {
    /// 65-byte secp256k1 signature in hex (0x-prefixed, 132 chars): r (32 bytes) + s (32 bytes) + v (1 byte). This is the format returned directly by `eth_signTypedData_v4` and all standard Ethereum signing libraries.
    pub signature: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PayerSignatureResponseGen {
    /// Payment identifier.
    pub payment_id: String,
    /// The address recovered from the signature — should match `payment.payer`. Included for client-side verification.
    pub recovered_payer: Option<String>,
    /// Confirms the signature was accepted and stored.
    pub status: String,
}

/// Immutable payment configuration that maps 1-to-1 to the RAIL0 `Payment` Solidity struct.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PaymentConfigGen {
    /// Exact amount the payer commits to pay (in token base units, fits in uint120).
    pub amount: String,
    /// Unix timestamp (seconds). Capture must happen before this; release opens after.
    pub authorization_expiry: i64,
    /// Fee in basis points (0 = no fee, 10000 = 100%).
    pub fee_bps: u32,
    /// Recipient of the fee on each capture. Use the zero address (0x0000…0000) when feeBps is 0.
    pub fee_receiver: String,
    /// Merchant address. Authorized to capture, void, and refund.
    pub payee: String,
    /// Buyer address. Funds are pulled from this address.
    pub payer: String,
    /// Unix timestamp (seconds). Refund must happen before this. Must be >= authorizationExpiry.
    pub refund_expiry: i64,
    /// EIP-3009-capable ERC-20 token address (must be accepted by the RAIL0 deployment).
    pub token: String,
}

/// Buyer-supplied payment parameters. Policy fields (amount, authorizationExpiry, refundExpiry, feeBps, feeReceiver) are fixed API configuration and are applied server-side — they are not accepted in input but appear in CreatePaymentResponse.payment.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PaymentInputGen {
    /// Merchant wallet address (walletAddress from GET /merchants/{id}/payment-methods).
    pub payee: String,
    /// Buyer address. Funds are pulled from this address.
    pub payer: String,
    /// ERC-20 token address (tokenAddress from GET /merchants/{id}/payment-methods).
    pub token: String,
}

/// A single accepted payment method for a merchant: one (chain, token, wallet) combination.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PaymentMethodGen {
    /// EVM chain ID, derived from the token record.
    pub chain_id: u32,
    /// Human-readable chain name.
    pub chain_name: String,
    /// MERCHANT_WALLETS row identifier.
    pub id: u32,
    /// True for the merchant's pre-selected payment method.
    pub is_default: bool,
    /// ERC-20 token contract address on the chain.
    pub token_address: String,
    /// Token decimal places.
    pub token_decimals: u32,
    /// TOKENS row identifier (tokens.id).
    pub token_id: u32,
    /// Token ticker symbol.
    pub token_symbol: String,
    /// Merchant wallet address to use as `payee` in PaymentConfig.
    pub wallet_address: String,
}

/// An unsigned EIP-1559 transaction ready for the payee to sign. Signing options: (a) wallet users pass `unsignedTransaction` to `eth_signTransaction`; (b) backends with direct key access sign the RLP blob with any secp256k1 library (e.g. `wallet.signTransaction` in ethers.js). Submit the resulting signed RLP to the corresponding `/submit` endpoint.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PrepareTransactionResponseGen {
    /// EVM chain ID.
    pub chain_id: u32,
    /// ABI-encoded calldata (informational; already encoded in `unsignedTransaction`).
    pub data: String,
    /// Estimated gas limit with a safety margin.
    pub gas_limit: String,
    /// EIP-1559 max fee per gas (wei).
    pub max_fee_per_gas: String,
    /// EIP-1559 max priority fee per gas (wei).
    pub max_priority_fee_per_gas: String,
    /// Transaction nonce for the payee's account.
    pub nonce: u32,
    /// RAIL0 contract address (informational; already encoded in `unsignedTransaction`).
    pub to: String,
    /// RLP-encoded unsigned EIP-1559 transaction (type 2). Pass to `eth_signTransaction` (browser wallet) or sign directly with a secp256k1 library if the key is available in-process.
    pub unsigned_transaction: String,
}

/// Amount to refund to the payer. Must be > 0 and <= current refundableAmount.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RefundPaymentRequestGen {
    /// Amount to refund (in token base units). Must be > 0 and <= current refundableAmount.
    pub amount: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RefundPaymentResponseGen {
    /// Payment identifier.
    pub payment_id: String,
    /// Remaining refundable balance after this refund.
    pub refundable_amount: String,
    /// Amount refunded to the payer in this call.
    pub refunded_amount: String,
    /// On-chain transaction hash of the `refund()` call.
    pub transaction_hash: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ReleasePaymentResponseGen {
    /// Payment identifier.
    pub payment_id: String,
    /// Amount returned to the payer (was the full remaining capturableAmount).
    pub released_amount: String,
    /// On-chain transaction hash of the `release()` call.
    pub transaction_hash: String,
}

/// EIP-712 typed-data structure that the payer must sign. The `domain`, `types`, and `message` fields follow the EIP-712 standard. Signing options: (a) wallet users pass this object verbatim to `eth_signTypedData_v4`; (b) backends with direct key access compute `keccak256('\x19\x01' || domainSeparator || hashStruct(message))` with any EIP-712 library and sign with secp256k1. Both approaches produce the same 65-byte signature to submit to `PUT /payments/{paymentId}/sign`.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SigningPayloadGen {
    pub domain: String,
    pub message: String,
    /// EIP-712 primary type.
    pub primary_type: String,
    /// EIP-712 type definitions.
    pub types: serde_json::Value,
}

/// Signed transaction to submit on-chain.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SubmitTransactionRequestGen {
    /// RLP-encoded signed EIP-1559 transaction as returned by `eth_signTransaction`.
    pub signed_transaction: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct VoidPaymentResponseGen {
    /// Payment identifier.
    pub payment_id: String,
    /// Amount returned to the payer (was the full capturableAmount).
    pub released_amount: String,
    /// On-chain transaction hash of the `void()` call.
    pub transaction_hash: String,
}

